spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.225:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: 192.168.31.225
    port: 6379

